In [66]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [69]:
ar1=np.arange(4)
ar1

array([0, 1, 2, 3])

In [71]:
ar1=np.arange(4).reshape(2,2)

In [73]:
ar1

array([[0, 1],
       [2, 3]])

In [78]:
np.concatenate([ar1,ar1], axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [80]:
np.concatenate([ar1,ar1], axis=1)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [82]:
df1=DataFrame({
    'A':[1,2,3],
    'B':[4,5,6]
})
df1

A  B
0  1  4
1  2  5
2  3  6

In [84]:
df2=DataFrame({
    'A':[10,11],
    'B':[40,50]
})
df2

A   B
0  10  40
1  11  50

In [88]:
df3=DataFrame({
    'A':[40,50,60],
    'B':[70,80,90],
    'C':[10,11,12]
})
df3

A   B   C
0  40  70  10
1  50  80  11
2  60  90  12

In [105]:
pd.concat([df1,df2])

A   B
0  10  40
1  11  50
0   1   4
1   2   5
2   3   6

In [107]:
pd.concat([df1,df2],axis=1)

A     B  A  B
0  10.0  40.0  1  4
1  11.0  50.0  2  5
2   NaN   NaN  3  6

In [109]:
pd.concat([df1,df2], axis=1, join='inner')

A   B  A  B
0  10  40  1  4
1  11  50  2  5

In [114]:
pd.concat([df1,df2], axis=1, join='inner', keys=['one','two'])

one     two   
    A   B   A  B
0  10  40   1  4
1  11  50   2  5

In [119]:
pd.concat([df1,df2], axis=0, join='inner', keys=['one','two'])

A   B
one 0  10  40
    1  11  50
two 0   1   4
    1   2   5
    2   3   6

In [122]:
df1 = DataFrame({'A':[1,2,3,4],'B':[5,6,7,8], 'C':[9,10,11,12]})
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [126]:
df2 = DataFrame({'A':['a','b','c','d'],'B':['e','f','g','h'], 'C':['i','j','k','l']})
df2

A  B  C
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [127]:
df1.combine_first(df2)

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [6]:
list_1 = [1,2,3,4]

In [9]:
a = np.array(list_1)

In [11]:
a

array([1, 2, 3, 4])

In [14]:
b=np.array([[1,2,3],[4,5,6]])

In [16]:
print(b.shape)

(2, 3)


In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
lst=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [22]:
arr = np.array(lst)

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a= arr[1:, 1:]
a

array([[5, 6],
       [8, 9]])

In [61]:
a= arr[0:2, 0:2]
a

array([[1, 2],
       [4, 5]])

In [35]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])
bool_array

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [64]:
n = arr[bool_array]
n

array([2, 4, 6, 8])

In [44]:
a = np.array(lst)
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [48]:
print(a[bool_indexing])
n = a[a % 2 == 0]

[2 4 6 8]


In [52]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [53]:
b = np.arange(4,8).reshape(2,2)
b

array([[4, 5],
       [6, 7]])

In [55]:
c = a + b
c = np.add(a, b)
print(c) 

[[ 4  6]
 [ 8 10]]


In [57]:
c = a - b
c = np.subtract(a, b)
print(c)

[[-4 -4]
 [-4 -4]]


In [59]:
c = a * b
c = np.multiply(a, b)
print(c)

[[ 0  5]
 [12 21]]


In [60]:
c = a / b
c = np.divide(a, b)
print(c)

[[0.         0.2       ]
 [0.33333333 0.42857143]]
